services:
  - type: web
    name: lite-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/chromium
